version: '3.8'

services:
  fastapi_app:
    build: .
    container_name: factory_hub_user_management
    ports:
      - "8001:8001"
    networks:
      - factory_hub_network
    env_file:
      - .env
    volumes:
      - ./app:/app
    restart: always

networks:
  factory_hub_network:
    external: true
